#!/bin/bash

# SYMLINKS
mkdir -p ~/.config
ln -rs pacman ~/.config/

ln -rs i3 ~/.config/
ln -rs i3blocks ~/.config/

ln -rs autorandr ~/.config/

ln -rs termite ~/.config/

ln -rs ranger ~/.config/

ln -rs nvim ~/.config/
ln -rs nvim ~/.vim
ln -rs nvim/init.vim ~/.vimrc

rm ~/.bash_profile
rm ~/.bashrc

ln -rs bash_profile ~/.bash_profile
ln -rs bashrc ~/.bashrc
ln -rs xbindkeysrc ~/.xbindkeysrc
ln -rs xinitrc ~/.xinitrc
ln -rs Xresources ~/.Xresources

# include custom fonts
#mkdir -p ~/.local/share
#ln -rs fonts ~/.local/share/
#fc-cache -fv

# GIT
# set gitignore global
ln -rs gitignore-global ~/.gitignore
# set username und email
git config --global user.email "***REMOVED******REMOVED***"
git config --global user.name "***REMOVED***"

# INSTALLATION
# install plug.vim and create dirs
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# install more initial needed packages
yay -S acpi atool autorandr cups dmenu2 galculator git gnome-keyring google-chrome highlight hplip htop i3 i3blocks-contrib mediainfo mplayer neovim net-tools python-pynvim nfs-utils otf-font-awesome pavucontrol-qt pulseaudio pulseaudio-alsa ranger scrot sysstat termite ttf-dejavu ttf-droid ttf-roboto unrar unzip visual-studio-code-bin w3m wireless_tools xbindkeys xorg-server xorg-dpyinfo xorg-xinit xorg-xrandr #feh
