---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"

includes:
  install: .taskfiles/install.yaml
  maintenance: .taskfiles/maintenance.yaml
  symlinks: .taskfiles/symlinks.yaml

tasks:
  k9s-logs:
    desc: show k9s logs
    cmds:
      - tail -f $HOME/.local/state/k9s/k9s.log

  setup-coal:
    desc: setup coal
    cmds:
      - task: install:base
      - task: install:system
      - task: install:sway
      - task: install:devtools
      - task: symlinks:base
      - task: symlinks:apps
      - task: symlinks:secrets

  setup-purple:
    desc: setup purple
    cmds:
      - task: install:base
      - task: install:system
      - task: install:nvidia
      - task: install:sway
      - task: install:devtools
      - task: symlinks:base
      - task: symlinks:apps
      - task: symlinks:secrets

  setup-workstation:
    desc: setup workstation
    cmds:
      - task: install:workstation
      - task: symlinks:base
      - task: symlinks:apps
      - task: symlinks:secrets
      - mkdir -p ~/scripts && ln -rsf init.sh ~/scripts

  setup-wsl:
    desc: setup wsl
    cmds:
      - task: install:base
      # - task: install:devtools
      - task: symlinks:base
      - task: symlinks:apps
      - task: symlinks:secrets
