export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
export OBSIDIAN_VAULT_PATH=/srv/shared/documents

eval "$(command mise activate bash)"

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
ssh-add ~/.ssh/id_ed25519_sk_notouch 2>/dev/null

if command -v nvim > /dev/null 2>&1; then
  export EDITOR="nvim"
  alias vim="nvim"
fi

[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ll="ls -lh --color=auto"
alias la="ls -lah --color=auto"
alias grep="grep --color=auto"

PS1='\[\e[1;33m\]\t\[\e[0m\] \[\e[1;34m\]\u\[\e[0m\]\n\[\e[1;36m\]\w\[\e[0m\] \$ '
