# For more information on this configuration file, see containers.conf(5).

[containers]
privileged = false
read_only = true
userns = "auto"

[network]
default_rootless_network_cmd = "pasta"
pasta_options = ["--ipv4-only"]
