---
volumes:
  data:

configs:
  poll-config.yml:
    content: |
      - url: https://github.com/jazzlyn/dotfiles
        reference: main
        target: ${TARGET}
        interval: 180

services:
  doco-cd:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.114.0@sha256:73b60295d651745b1701003e19ce1d5114ebfeb3446dbc4e3aeb17882e1a3568
    restart: always
    configs:
      - source: poll-config.yml
        target: /poll-config.yml
    environment:
      TZ: Europe/Vienna
      LOG_LEVEL: info
      POLL_CONFIG_FILE: /poll-config.yml
      DEPLOY_CONFIG_BASE_DIR: ./docker
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    cap_drop:
      - ALL
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - data:/data
