---
volumes:
  data:

configs:
  poll-config.yml:
    content: |
      - url: https://github.com/jazzlyn/dotfiles
        reference: main
        target: ${TARGET}
        interval: 180
      - url: https://github.com/tyriis/home-ops
        reference: main
        target: ${TARGET}
        interval: 180

secrets:
  sops_age_key:
    file: ${SOPS_AGE_KEY_FILE:-/etc/doco-cd/age-keys.txt}
  webhook_secret:
    file: ${WEBHOOK_SECRET_FILE:-/etc/doco-cd/webhook_secret}
services:
  doco-cd:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.117.1@sha256:9db114c98e4fffa2f88a5ded0d4f71356334310057398f31105cabb004077e28
    restart: always
    configs:
      - source: poll-config.yml
        target: /poll-config.yml
    environment:
      TZ: Europe/Vienna
      LOG_LEVEL: info
      POLL_CONFIG_FILE: /poll-config.yml
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      DEPLOY_CONFIG_BASE_DIR: ./docker
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    secrets:
      - webhook_secret
      - sops_age_key
    cap_drop:
      - ALL
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - data:/data
