---
services:
  lgtm:
    image: grafana/otel-lgtm:0.30.0@sha256:46ca028e294bd728e8e930a28e887f640a8f2a9533cc283f79bcc6ab73d2ffd8
    container_name: lgtm
    environment:
      PROMETHEUS_EXTRA_ARGS: --storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-15d}
      LOKI_EXTRA_ARGS: --store.retention=${LOKI_RETENTION_TIME:-15d}
      TEMPO_EXTRA_ARGS: --backend-worker.compaction.block-retention=${TEMPO_RETENTION_TIME:-24h}
      ENABLE_LOGS_GRAFANA: "true"
      ENABLE_LOGS_OTELCOL: "true"
      ENABLE_LOGS_LOKI: "true"
      ENABLE_LOGS_TEMPO: "true"
      ENABLE_LOGS_PROMETHEUS: "true"
    volumes:
      - ./loki-config.yaml:/otel-lgtm/loki-config.yaml:ro
      - lgtm-data:/data
    ports:
      - "127.0.0.1:3000:3000" # Grafana
      - "127.0.0.1:3200:3200" # Tempo
      - "127.0.0.1:4317:4317" # OTLP gRPC
      - "127.0.0.1:4318:4318" # OTLP HTTP
      - "127.0.0.1:9090:9090" # Prometheus
    networks:
      - observability
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #     reservations:
    #       memory: 512M

volumes:
  lgtm-data:

networks:
  observability:
    name: observability
