export BUN_INSTALL_CACHE_DIR=$XDG_CACHE_HOME/bun/install/cache
export BUN_INSTALL_GLOBAL_DIR=$XDG_DATA_HOME/bun/install/global
export BUN_INSTALL_GLOBAL_BIN_DIR=$XDG_DATA_HOME/bin
export PATH="$PATH:$BUN_INSTALL_GLOBAL_BIN_DIR"
