SPACESHIP_PROMPT_ORDER=(
  time
  user
  host
  git
  golang
  node
  python
  docker
  docker_compose
  venv
  aws
  azure
  gcloud
  kubectl
  terraform
  nix_shell
  exit_code
  line_sep
  dir
  char
)

# BASE PROMPT

## PROMPT
SPACESHIP_PROMPT_ASYNC=false
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_PREFIXES_SHOW=false

## CHAR
SPACESHIP_CHAR_SYMBOL="$"
# SPACESHIP_CHAR_COLOR_SUCCESS="green"
# SPACESHIP_CHAR_COLOR_FAILURE="red"
# SPACESHIP_CHAR_COLOR_SECONDARY="yellow"

## TIME
SPACESHIP_TIME_SHOW=true
# SPACESHIP_TIME_COLOR="yellow"

## USER
SPACESHIP_USER_SHOW="always"
SPACESHIP_USER_SUFFIX="@"
SPACESHIP_USER_COLOR="magenta"
SPACESHIP_USER_COLOR_ROOT="red"

## HOST
SPACESHIP_HOST_SHOW="always"
SPACESHIP_HOST_COLOR="magenta"
SPACESHIP_HOST_COLOR_SSH="yellow"

## DIR
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_DIR_COLOR="cyan"
SPACESHIP_DIR_LOCK_COLOR="red"

# SECTIONS

# AWS
SPACESHIP_AWS_COLOR="208"

# AZURE
SPACESHIP_AZURE_COLOR="039"

# DOCKER
# SPACESHIP_DOCKER_COLOR="cyan"

# GIT
SPACESHIP_GIT_BRANCH_COLOR="blue"

# GOLANG
# SPACESHIP_GOLANG_COLOR="cyan"

# GOOGLE CLOUD
SPACESHIP_GCLOUD_COLOR="026"

# KUBECTL
SPACESHIP_KUBECTL_SHOW=true
## KUBECTL version
SPACESHIP_KUBECTL_VERSION_SHOW=false
## KUBECTL context
SPACESHIP_KUBECTL_CONTEXT_COLOR="#3371e3"
SPACESHIP_KUBECTL_CONTEXT_SHOW_NAMESPACE=false

# NIX SHELL
# SPACESHIP_NIX_SHELL_COLOR="yellow"

# NODE
# SPACESHIP_NODE_COLOR="green"

# PYTHON
# SPACESHIP_PYTHON_COLOR="yellow"

# TERRAFORM
# SPACESHIP_TERRAFORM_COLOR="105"

# VENV
# SPACESHIP_VENV_COLOR="blue"

# EXIT CODE
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL="✘ "
# SPACESHIP_EXIT_CODE_COLOR="red"
