SPACESHIP_PROMPT_ORDER=(
  time
  user
  host
  git
  node
  golang
  docker
  aws
  gcloud
  kubectl
  terraform
  nix_shell
  exit_code
  line_sep
  dir
  char
)

# BASE PROMPT

SPACESHIP_PROMPT_ASYNC=false

## PROMPT
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=false
SPACESHIP_PROMPT_PREFIXES_SHOW=true
SPACESHIP_PROMPT_SUFFIXES_SHOW=true
SPACESHIP_PROMPT_DEFAULT_PREFIX=" "
SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "

## CHAR
SPACESHIP_CHAR_PREFIX=""
SPACESHIP_CHAR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_CHAR_SYMBOL="$"
SPACESHIP_CHAR_SYMBOL_ROOT="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_SYMBOL_SECONDARY="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_COLOR_SUCCESS="green"
SPACESHIP_CHAR_COLOR_FAILURE="red"
SPACESHIP_CHAR_COLOR_SECONDARY="yellow"

## TIME
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_PREFIX="at "
SPACESHIP_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_TIME_12HR=false
SPACESHIP_TIME_COLOR="yellow"

## USER
SPACESHIP_USER_SHOW="never"
SPACESHIP_USER_PREFIX=""
SPACESHIP_USER_SUFFIX="@"
SPACESHIP_USER_COLOR="magenta"
SPACESHIP_USER_COLOR_ROOT="red"

## HOST
SPACESHIP_HOST_SHOW="always"
SPACESHIP_HOST_SHOW_FULL=false
SPACESHIP_HOST_PREFIX=""
SPACESHIP_HOST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_HOST_COLOR="magenta"
SPACESHIP_HOST_COLOR_SSH="yellow"

## DIR
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DIR_TRUNC=3
SPACESHIP_DIR_TRUNC_PREFIX=""
SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_DIR_COLOR="cyan"
SPACESHIP_DIR_LOCK_SYMBOL=""
SPACESHIP_DIR_LOCK_COLOR="red"

# SECTIONS

## AWS
SPACESHIP_AWS_SHOW=true
SPACESHIP_AWS_PREFIX=""
SPACESHIP_AWS_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_AWS_COLOR="#ff9d00"

## DOCKER
SPACESHIP_DOCKER_SHOW=true
SPACESHIP_DOCKER_PREFIX=""
SPACESHIP_DOCKER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DOCKER_COLOR="#0db7ed"

## DOCKER context
SPACESHIP_DOCKER_CONTEXT_SHOW=true
SPACESHIP_DOCKER_CONTEXT_PREFIX=" ("
SPACESHIP_DOCKER_CONTEXT_SUFFIX=")"

## GIT
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GIT_SYMBOL=" "
## GIT BRANCH
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_BRANCH_PREFIX="$SPACESHIP_GIT_SYMBOL"
SPACESHIP_GIT_BRANCH_SUFFIX=""
SPACESHIP_GIT_BRANCH_COLOR="blue"
## GIT STATUS
SPACESHIP_GIT_STATUS_SHOW=true
SPACESHIP_GIT_STATUS_PREFIX=" ["
SPACESHIP_GIT_STATUS_SUFFIX="]"
SPACESHIP_GIT_STATUS_COLOR="red"
SPACESHIP_GIT_STATUS_UNTRACKED="?"
SPACESHIP_GIT_STATUS_ADDED="+"
SPACESHIP_GIT_STATUS_MODIFIED="!"
SPACESHIP_GIT_STATUS_RENAMED="»"
SPACESHIP_GIT_STATUS_DELETED="✘"
SPACESHIP_GIT_STATUS_STASHED="$"
SPACESHIP_GIT_STATUS_UNMERGED="="
SPACESHIP_GIT_STATUS_AHEAD="⇡"
SPACESHIP_GIT_STATUS_BEHIND="⇣"
SPACESHIP_GIT_STATUS_DIVERGED="⇕"

## GCLOUD
SPACESHIP_GCLOUD_SHOW=true
SPACESHIP_GCLOUD_PREFIX=""
SPACESHIP_GCLOUD_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GCLOUD_COLOR="ffffff"

## GOLANG
SPACESHIP_GOLANG_SHOW=true
SPACESHIP_GOLANG_PREFIX=""
SPACESHIP_GOLANG_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GOLANG_COLOR="cyan"

## KUBECTL
SPACESHIP_KUBECTL_SHOW=true
SPACESHIP_KUBECTL_PREFIX=""
SPACESHIP_KUBECTL_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_KUBECTL_COLOR="#3371e3"

## KUBECTL version
SPACESHIP_KUBECTL_VERSION_SHOW=false
## KUBECTL context
SPACESHIP_KUBECTL_CONTEXT_SHOW=true
SPACESHIP_KUBECTL_CONTEXT_PREFIX=""
SPACESHIP_KUBECTL_CONTEXT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_KUBECTL_CONTEXT_SHOW_NAMESPACE=false
SPACESHIP_KUBECTL_CONTEXT_COLOR="#3371e3"#

## NIX SHELL
SPACESHIP_NIX_SHELL_SHOW=true
SPACESHIP_NIX_SHELL_PREFIX=""
SPACESHIP_NIX_SHELL_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_NIX_SHELL_COLOR="yellow"

## NODE
SPACESHIP_NODE_SHOW=true
SPACESHIP_NODE_PREFIX=""
SPACESHIP_NODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_NODE_COLOR="green"

## PYTHON
SPACESHIP_PYTHON_SHOW=true
SPACESHIP_PYTHON_PREFIX=""
SPACESHIP_PYTHON_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_PYTHON_COLOR="yellow"

## TERRAFORM
SPACESHIP_TERRAFORM_SHOW=true
SPACESHIP_TERRAFORM_PREFIX=""
SPACESHIP_TERRAFORM_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_TERRAFORM_COLOR="#844fba"

# EXIT CODE
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_PREFIX="("
SPACESHIP_EXIT_CODE_SUFFIX=") "
SPACESHIP_EXIT_CODE_SYMBOL="✘ "
SPACESHIP_EXIT_CODE_COLOR="red"
