monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-SteelSeries_Arctis_Pro_Wireless.*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 5000
        priority.session = 5000
      }
    }
  }
]
