---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry run mode
        type: choice
        options:
          - "null"
          - extract
          - lookup
          - full
        default: "null"
        required: false
      log-level:
        description: renovate log level
        type: choice
        options:
          - debug
          - info
          - warn
          - error
          - fatal
        default: debug
        required: false
  schedule:
    - cron: 0 */6 * * * # every 6 hours
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate-bot.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # https://github.com/marketplace/actions/harden-runner
      - name: harden runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        with:
          app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # https://github.com/marketplace/actions/renovate-bot-github-action
      - name: renovate bot
        uses: renovatebot/github-action@3f10d7a25cf0aa7b37519aa771ed9143fcbb5da5 # v41.0.10
        env:
          LOG_LEVEL: ${{ inputs.log-level || 'debug' }}
          RENOVATE_CONFIG_FILE: .github/renovate-bot.json5
          RENOVATE_DRY_RUN: ${{ inputs.dry-run || 'null' }}
          RENOVATE_TOKEN: ${{ steps.generate-token.outputs.token }}
